version: '3'

services:
  mariadb:
    image: mariadb:10.4
    command: ['--interactive_timeout=28800', '--wait_timeout=28800']
    environment:
      MYSQL_DATABASE: breezy
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./docker:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306